DROP TABLE IF EXISTS MASTER;
CREATE TABLE MASTER(
    UID CHARACTER PRIMARY KEY,
    COLUMN_A INT,
    COLUMN_B INT,
    COLUMN_C INT,
    COLUMN_D CHARACTER,
    MODIFIED_DATE TIMESTAMP
);

--DROP TABLE IF EXISTS MASTER;
--CREATE TABLE IF NOT EXISTS `master` (
--  `UID` char(5) NOT NULL,
--  `COLUMN_A` int,
--  `COLUMN_B` int,
--  `COLUMN_C` int,
--  `COLUMN_D` char(5),
--  `MODIFIED_DATE` TIMESTAMP(6),
--  PRIMARY KEY (`UID`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8;