DROP TABLE IF EXISTS MASTER;
CREATE TABLE MASTER(
    UID CHARACTER PRIMARY KEY,
    COLUMN_A INT,
    COLUMN_B INT,
    COLUMN_C INT,
    COLUMN_D CHARACTER,
    MODIFIED_DATE TIMESTAMP
);

DROP TABLE IF EXISTS PLAYER;
CREATE TABLE PLAYER(
    ID BIGINT PRIMARY KEY,
    MMR INT
);

DROP TABLE IF EXISTS STATISTIC;
CREATE TABLE STATISTIC(
    ID INT PRIMARY KEY,
    TOTAL INT
);
INSERT INTO STATISTIC VALUES(0, 0);