DROP TABLE IF EXISTS PLAYER;
CREATE TABLE PLAYER(
    ID BIGINT PRIMARY KEY,
    MMR INT
);

DROP TABLE IF EXISTS STATISTIC;
CREATE TABLE STATISTIC(
    ID INT PRIMARY KEY,
    TOTAL INT
);
INSERT INTO STATISTIC VALUES(0, 0);